service: serverlessBackend

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    ENVIRONMENT: ${env:ENVIRONMENT, 'local'}

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

functions:
  authorizerFunc:
    handler: authorizer.auth
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            type: request
            identitySource: method.request.header.X-Nf-Sign
plugins:
  - serverless-offline
